// File: mux2x1_scalar.v
// Generated by MyHDL 0.11.42
// Date: Mon Dec 11 01:38:18 2023


`timescale 1ns/10ps

module mux2x1_scalar (
    y,
    a,
    b,
    sel
);
// Multiplexer
// 
// y -- scalar data output
// a, b -- scalar data inputs
// sel -- control input: select a if asserted, otherwise b

output y;
reg y;
input a;
input b;
input sel;




always @(b, a, sel) begin: MUX2X1_SCALAR_COMB
    if ((sel == 1)) begin
        y = b;
    end
    else begin
        y = a;
    end
end

endmodule
