// File: ha.v
// Generated by MyHDL 0.11.42
// Date: Sun Dec 10 21:35:42 2023


`timescale 1ns/10ps

module ha (
    a,
    b,
    sum,
    co
);
// Half Adder
// sum,co - outputs
// a,b - inputs

input a;
input b;
output sum;
reg sum;
output co;
reg co;




always @(b, a) begin: HA_COMB
    if (((a == 0) && (b == 0))) begin
        sum = 0;
        co = 0;
    end
    else if (((a == 0) && (b == 1))) begin
        sum = 1;
        co = 0;
    end
    else if (((a == 1) && (b == 0))) begin
        sum = 1;
        co = 0;
    end
    else begin
        sum = 0;
        co = 1;
    end
end

endmodule
