// File: orgate.v
// Generated by MyHDL 0.11.42
// Date: Sun Dec 10 21:35:42 2023


`timescale 1ns/10ps

module orgate (
    a,
    b,
    y
);
// OR Gate
// y - outputs
// a,b - inputs

input a;
input b;
output y;
reg y;




always @(b, a) begin: ORGATE_COMB
    if (((a == 0) && (b == 0))) begin
        y = 0;
    end
    else if (((a == 0) && (b == 1))) begin
        y = 1;
    end
    else if (((a == 1) && (b == 0))) begin
        y = 1;
    end
    else begin
        y = 1;
    end
end

endmodule
