// File: mux2x1_vectored.v
// Generated by MyHDL 0.11.42
// Date: Mon Dec 11 01:32:55 2023


`timescale 1ns/10ps

module mux2x1_vectored (
    y,
    a,
    b,
    sel
);
// Multiplexer 2x1
// y -- mux output
// a, b -- data inputs
// sel -- control input: select b if asserted, otherwise a

output [7:0] y;
reg [7:0] y;
input [7:0] a;
input [7:0] b;
input sel;




always @(sel, b, a) begin: MUX2X1_VECTORED_COMB
    if ((sel == 1)) begin
        y = b;
    end
    else begin
        y = a;
    end
end

endmodule
