// File: mux.v
// Generated by MyHDL 0.11.42
// Date: Sun Dec 10 11:54:49 2023


`timescale 1ns/10ps

module mux (
    z,
    a,
    b,
    sel
);
// Multiplexer.
// 
// z -- mux output
// a, b -- data inputs
// sel -- control input: select a if asserted, otherwise b

output z;
reg z;
input a;
input b;
input sel;




always @(a, b, sel) begin: MUX_COMB
    if ((sel == 0)) begin
        z = a;
    end
    else begin
        z = b;
    end
end

endmodule
