// File: muxvectored.v
// Generated by MyHDL 0.11.42
// Date: Sun Dec 10 12:17:24 2023


`timescale 1ns/10ps

module muxvectored (
    y,
    a,
    b,
    sel
);
// Multiplexer.
// 
// y -- mux output
// a, b -- data inputs
// sel -- control input: select a if asserted, otherwise b

output [4:0] y;
reg [4:0] y;
input [4:0] a;
input [4:0] b;
input sel;




always @(a, b, sel) begin: MUXVECTORED_COMB
    if ((sel == 0)) begin
        y = a;
    end
    else begin
        y = b;
    end
end

endmodule
